// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {ipc} from '../models';

export function CheckConnectionStatus():Promise<Record<string, any>>;

export function CheckWindowsAutoStart():Promise<boolean>;

export function ConnectDevice():Promise<boolean>;

export function DisconnectDevice():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetAvailableGears():Promise<Record<string, Array<types.GearCommand>>>;

export function GetBridgeProgramStatus():Promise<Record<string, any>>;

export function GetConfig():Promise<types.AppConfig>;

export function GetCurrentFanData():Promise<types.FanData>;

export function GetDebugInfo():Promise<Record<string, any>>;

export function GetDeviceStatus():Promise<Record<string, any>>;

export function GetFanCurve():Promise<Array<types.FanCurvePoint>>;

export function GetTemperature():Promise<types.TemperatureData>;

export function HideWindow():Promise<void>;

export function InitSystemTray():Promise<void>;

export function IsAutoStartLaunch():Promise<boolean>;

export function LogFrontendError(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function QuitApp():Promise<void>;

export function RestartCoreService():Promise<boolean>;

export function SetAutoControl(arg1:boolean):Promise<void>;

export function SetBrightness(arg1:number):Promise<boolean>;

export function SetCustomSpeed(arg1:boolean,arg2:number):Promise<void>;

export function SetDebugMode(arg1:boolean):Promise<void>;

export function SetFanCurve(arg1:Array<types.FanCurvePoint>):Promise<void>;

export function SetGearLight(arg1:boolean):Promise<boolean>;

export function SetManualGear(arg1:string,arg2:string):Promise<boolean>;

export function SetPowerOnStart(arg1:boolean):Promise<boolean>;

export function SetRGBMode(arg1:ipc.SetRGBModeParams):Promise<boolean>;

export function SetSmartStartStop(arg1:string):Promise<boolean>;

export function SetWindowsAutoStart(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StopCoreService():Promise<boolean>;

export function TestBridgeProgram():Promise<types.BridgeTemperatureData>;

export function TestTemperatureReading():Promise<types.TemperatureData>;

export function UpdateConfig(arg1:types.AppConfig):Promise<void>;

export function UpdateGuiResponseTime():Promise<void>;
