// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnectionStatus() {
  return window['go']['main']['App']['CheckConnectionStatus']();
}

export function CheckWindowsAutoStart() {
  return window['go']['main']['App']['CheckWindowsAutoStart']();
}

export function ConnectDevice() {
  return window['go']['main']['App']['ConnectDevice']();
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAvailableGears() {
  return window['go']['main']['App']['GetAvailableGears']();
}

export function GetBridgeProgramStatus() {
  return window['go']['main']['App']['GetBridgeProgramStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentFanData() {
  return window['go']['main']['App']['GetCurrentFanData']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetDeviceStatus() {
  return window['go']['main']['App']['GetDeviceStatus']();
}

export function GetFanCurve() {
  return window['go']['main']['App']['GetFanCurve']();
}

export function GetTemperature() {
  return window['go']['main']['App']['GetTemperature']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InitSystemTray() {
  return window['go']['main']['App']['InitSystemTray']();
}

export function IsAutoStartLaunch() {
  return window['go']['main']['App']['IsAutoStartLaunch']();
}

export function LogFrontendError(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LogFrontendError'](arg1, arg2, arg3, arg4);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RestartCoreService() {
  return window['go']['main']['App']['RestartCoreService']();
}

export function SetAutoControl(arg1) {
  return window['go']['main']['App']['SetAutoControl'](arg1);
}

export function SetBrightness(arg1) {
  return window['go']['main']['App']['SetBrightness'](arg1);
}

export function SetCustomSpeed(arg1, arg2) {
  return window['go']['main']['App']['SetCustomSpeed'](arg1, arg2);
}

export function SetDebugMode(arg1) {
  return window['go']['main']['App']['SetDebugMode'](arg1);
}

export function SetFanCurve(arg1) {
  return window['go']['main']['App']['SetFanCurve'](arg1);
}

export function SetGearLight(arg1) {
  return window['go']['main']['App']['SetGearLight'](arg1);
}

export function SetManualGear(arg1, arg2) {
  return window['go']['main']['App']['SetManualGear'](arg1, arg2);
}

export function SetPowerOnStart(arg1) {
  return window['go']['main']['App']['SetPowerOnStart'](arg1);
}

export function SetRGBMode(arg1) {
  return window['go']['main']['App']['SetRGBMode'](arg1);
}

export function SetSmartStartStop(arg1) {
  return window['go']['main']['App']['SetSmartStartStop'](arg1);
}

export function SetWindowsAutoStart(arg1) {
  return window['go']['main']['App']['SetWindowsAutoStart'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopCoreService() {
  return window['go']['main']['App']['StopCoreService']();
}

export function TestBridgeProgram() {
  return window['go']['main']['App']['TestBridgeProgram']();
}

export function TestTemperatureReading() {
  return window['go']['main']['App']['TestTemperatureReading']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateGuiResponseTime() {
  return window['go']['main']['App']['UpdateGuiResponseTime']();
}
